"""Tests for judge blindness audit."""

import pytest
from src.evaluation.llm_judge_prompt import PROHIBITED_TERMS, validate_prompt_safety


class TestJudgeBlindness:
    """Tests for judge blindness validation."""

    def test_prohibited_terms_defined(self):
        """Test that prohibited terms are defined."""
        assert len(PROHIBITED_TERMS) > 0
        assert "system_name" in PROHIBITED_TERMS
        assert "human_score" in PROHIBITED_TERMS
        assert "openai" in PROHIBITED_TERMS

    def test_safe_input_passes(self):
        """Test that safe input passes blindness check."""
        safe_input = "I want to return this item. Can you help?"
        is_safe, violations = validate_prompt_safety(safe_input)
        assert is_safe
        assert len(violations) == 0

    def test_system_name_detected(self):
        """Test that system_name is detected."""
        is_safe, violations = validate_prompt_safety("This is from system_name: test")
        assert not is_safe
        assert any("system_name" in v for v in violations)

    def test_human_score_detected(self):
        """Test that human_score is detected."""
        is_safe, violations = validate_prompt_safety("The human_score was 4.5")
        assert not is_safe
        assert any("human_score" in v for v in violations)

    def test_model_name_detected(self):
        """Test that model names are detected."""
        is_safe, violations = validate_prompt_safety("Generated by gpt-4")
        assert not is_safe

    def test_provider_detected(self):
        """Test that provider names are detected."""
        is_safe, violations = validate_prompt_safety("Using OpenAI API")
        assert not is_safe

    def test_case_insensitive(self):
        """Test that detection is case insensitive."""
        is_safe, violations = validate_prompt_safety("SYSTEM_NAME is here")
        assert not is_safe

    def test_multiple_violations(self):
        """Test that multiple violations are caught."""
        text = "system_name and human_score are here"
        is_safe, violations = validate_prompt_safety(text)
        assert not is_safe
        assert len(violations) >= 2